// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD28S-WOYAM5qu59MDiDtXu7bo2C7ahsak',
    appId: '1:124430406638:web:339f100e4feb1ac16f74ff',
    messagingSenderId: '124430406638',
    projectId: 'chatapp-cd2e2',
    authDomain: 'chatapp-cd2e2.firebaseapp.com',
    storageBucket: 'chatapp-cd2e2.appspot.com',
    measurementId: 'G-BG1BP7Z0CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYYbChMPKgszk4QMOy8g7NIlR6yXbts0',
    appId: '1:124430406638:android:484025f2933b1cf96f74ff',
    messagingSenderId: '124430406638',
    projectId: 'chatapp-cd2e2',
    storageBucket: 'chatapp-cd2e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclL6lO3WF9kp7ALfzvyHwz8VsYeM4nSM',
    appId: '1:124430406638:ios:d0485edc97ea51876f74ff',
    messagingSenderId: '124430406638',
    projectId: 'chatapp-cd2e2',
    storageBucket: 'chatapp-cd2e2.appspot.com',
    iosClientId: '124430406638-48gvl436qee6rfpru40182snpnm4vinn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclL6lO3WF9kp7ALfzvyHwz8VsYeM4nSM',
    appId: '1:124430406638:ios:d0485edc97ea51876f74ff',
    messagingSenderId: '124430406638',
    projectId: 'chatapp-cd2e2',
    storageBucket: 'chatapp-cd2e2.appspot.com',
    iosClientId: '124430406638-48gvl436qee6rfpru40182snpnm4vinn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );
}
